### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by aoor9** [dhavalveera/dv-social-share#21]
I know there's already a types file, but what about migrating the whole project to Typescript?

**Comment by dhavalveera** [comment]
Thanks @aoor9 for the suggestion, I will migrate the Project to the TypeScript slowly, will need some time on it

**Comment by aoor9** [comment]
Do you accept PR for this goal?

**Comment by dhavalveera** [comment]
Yes, I accept PR as it's an Open Source, if you like to contribute, else I'll work on this on this weekend!

**Comment by dhavalveera** [comment]
I'll switch to TS this weekend! and can you add more Buttons for share? @aoor9

**Comment by dhavalveera** [comment]
I accept PR as it's an Open Source Project!

**Comment by dhavalveera** [comment]
@aoor9 - I've migrated the whole Project to the TypeScript! Thanks
